-- catalog-tier-a-2026-08 — REVIEW REQUIRED, DO NOT APPLY UNREVIEWED.
--
-- Generated by tool/catalog/bin/build_tier_seed.dart from
-- tool/catalog/out/catalog_tier_a_manifest.json
-- Portion policy: portion-policy-v2.
-- Curated by: recepzgrmh <zgrhdr@gmail.com> at 2026-08-21T09:15:26Z
--
-- Every row is verification_status = needs_review and reviewed_by =
-- null. Curating the mapping is not reviewing the output.
-- Prerequisite migration: 20260818220000_food_catalog_portion_references.sql
insert into public.catalog_import_batches (source, source_release, status, record_count, checksum, metadata)
values ('turkomp-tuber', 'catalog-tier-a-2026-08', 'staged', 198, 'a339fd99f61fd4fdc97bc0c8bd78fd12d0fbd87a7303b328dea1f53f4e049a80', '{"portionPolicyVersion":"portion-policy-v2","selectionRulesVersion":"catalog-selection-v1","curatedBy":"recepzgrmh <zgrhdr@gmail.com>","counts":{"foods":200,"portions":600,"publishedPortionFoods":93,"derivedEnergyEquivalentFoods":0,"blockedFoods":107,"blocked":321,"needsReview":279,"verified":0}}'::jsonb)
on conflict (source, source_release, checksum) do update set record_count = excluded.record_count, metadata = excluded.metadata;
