-- catalog-tier-a-2026-08 — REVIEW REQUIRED, DO NOT APPLY UNREVIEWED.
--
-- Generated by tool/catalog/bin/build_tier_seed.dart from
-- tool/catalog/out/catalog_tier_a_manifest.json
-- Portion policy: portion-policy-v2.
-- Curated by: recepzgrmh <zgrhdr@gmail.com> at 2026-08-21T09:15:26Z
--
-- Every row is verification_status = needs_review and reviewed_by =
-- null. Curating the mapping is not reviewing the output.
-- Prerequisite migration: 20260818220000_food_catalog_portion_references.sql
-- The curated-demo records carry unsourced macros and own aliases the
-- sourced records also claim. food_aliases is unique on
-- (alias, locale, food_id), so both would answer the same search.
-- Deactivated rather than deleted: aliases and portions cascade on
-- delete, is_active is already the search filter, and historical
-- meal_items.food_id references must survive.
update public.foods set is_active = false, updated_at = now()
 where source = 'curated-demo'
   and source_food_id in ('egg-boiled', 'white-cheese-full-fat', 'simit');
