-- catalog-tier-a-2026-08 — REVIEW REQUIRED, DO NOT APPLY UNREVIEWED.
--
-- Generated by tool/catalog/bin/build_tier_seed.dart from
-- tool/catalog/out/catalog_tier_a_manifest.json
-- Portion policy: portion-policy-v2.
-- Curated by: recepzgrmh <zgrhdr@gmail.com> at 2026-08-21T09:15:26Z
--
-- Every row is verification_status = needs_review and reviewed_by =
-- null. Curating the mapping is not reviewing the output.
-- Prerequisite migration: 20260818220000_food_catalog_portion_references.sql
-- psql "$DB_URL" -v ON_ERROR_STOP=1 -f _apply.sql
\ir 000_batch.sql
\ir 010_foods.sql
\ir 020_aliases.sql
\ir 030_portions.sql
\ir 050_source_records.sql
\ir 090_deactivate_curated_demo.sql
