// Generated by scripts/generate-mobile-copy-catalog.mjs. Do not edit manually.
export const mobileCopyCatalog = [
  {
    "key": "activeDaysCount",
    "tr": "{count} aktif gün",
    "en": "{count} active days",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "activeDaysProgress",
    "tr": "{count} / 3 aktif gün",
    "en": "{count} / 3 active days",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "activityTitle",
    "tr": "Aktivite",
    "en": "Activity",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "addByTyping",
    "tr": "Yazarak ekle",
    "en": "Add by typing",
    "source": "lib/src/app.dart"
  },
  {
    "key": "addMissingFoodAction",
    "tr": "Eksik yiyecek ekle",
    "en": "Add missing food",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "analysisEarlyTrend",
    "tr": "Bu ilk eğilim; daha fazla aktif gün eklendikçe daha güvenilir olacak.",
    "en": "This is an early trend; it will become more reliable as you add active days.",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "analysisEmptyAction",
    "tr": "Öğün ekle",
    "en": "Add a meal",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "analysisEmptyBody",
    "tr": "Öğün ekledikçe kalori trendin ve dönem karşılaştırman burada oluşacak.",
    "en": "Your calorie trend and period comparison will appear here as you add meals.",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "analysisEmptyTitle",
    "tr": "Bu dönemde kayıt yok",
    "en": "No entries in this period",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "analysisInProgress",
    "tr": "Öğünün çözümleniyor…",
    "en": "Analyzing your meal…",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "analysisInsufficientBody",
    "tr": "Beslenme değişimini gösterebilmemiz için birkaç farklı günde öğün kaydetmen gerekiyor.",
    "en": "Log meals on a few different days so we can show how your nutrition changes.",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "analysisInsufficientTitle",
    "tr": "Henüz yeterli veri yok",
    "en": "Not enough data yet",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "analysisPeriodMeals",
    "tr": "Dönemdeki öğünler",
    "en": "Meals in this period",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "analysisTitle",
    "tr": "Analiz",
    "en": "Analysis",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "analyzePhotoAction",
    "tr": "Öğünü analiz et",
    "en": "Analyze meal",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "applyAction",
    "tr": "Uygula",
    "en": "Apply",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "appTitle",
    "tr": "Meal Clarity",
    "en": "Meal Clarity",
    "source": "ARB"
  },
  {
    "key": "authChangeEmailAction",
    "tr": "E-postayı değiştir",
    "en": "Change email",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authEmailBody",
    "tr": "Şifre yok. Sana tek kullanımlık 6 haneli bir kod göndereceğiz.",
    "en": "No password. We will send you a one-time six-digit code.",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authEmailHint",
    "tr": "sen@ornek.com",
    "en": "you@example.com",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authEmailLabel",
    "tr": "E-posta",
    "en": "Email",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authEmailTitle",
    "tr": "E-postanla devam et.",
    "en": "Continue with your email.",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authErrorEmailDelivery",
    "tr": "Doğrulama e-postası şu anda gönderilemedi. Biraz sonra tekrar dene.",
    "en": "The verification email could not be sent right now. Please try again shortly.",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authErrorEmailLimit",
    "tr": "E-posta gönderim sınırına ulaşıldı. Daha önce gelen kod hâlâ geçerliyse onu kullanabilirsin.",
    "en": "The email sending limit was reached. If your previous code is still valid, you can use it.",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authErrorExpiredOtp",
    "tr": "Kodun süresi dolmuş. Yeni bir kod iste.",
    "en": "The code has expired. Request a new one.",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authErrorInvalidEmail",
    "tr": "Geçerli bir e-posta adresi gir.",
    "en": "Enter a valid email address.",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authErrorInvalidOtp",
    "tr": "Kod geçersiz. Kontrol edip tekrar dene.",
    "en": "The code is invalid. Check it and try again.",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authErrorNetwork",
    "tr": "Bağlantı zaman aşımına uğradı. Tekrar dene.",
    "en": "The connection timed out. Try again.",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authErrorRateLimited",
    "tr": "Çok sık deneme yapıldı. Geri sayım bitince tekrar dene.",
    "en": "Too many attempts. Try again when the countdown ends.",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authErrorUnknown",
    "tr": "İşlem tamamlanamadı. Lütfen tekrar dene.",
    "en": "The operation could not be completed. Please try again.",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authLegalNotice",
    "tr": "Devam ederek Kullanım Koşulları ve Gizlilik Politikasını kabul edersin.",
    "en": "By continuing, you agree to the Terms of Use and Privacy Policy.",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authLimitCountdownDetail",
    "tr": "Yeni istek: yaklaşık {time} sonra",
    "en": "New request: in about {time}",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authOtpBody",
    "tr": "6 haneli kodu {email} adresine gönderdik.",
    "en": "We sent a six-digit code to {email}.",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authOtpLabel",
    "tr": "6 haneli kod",
    "en": "6-digit code",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authOtpTitle",
    "tr": "Kodunu kontrol et.",
    "en": "Check your code.",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authResendCodeAction",
    "tr": "Yeniden gönder",
    "en": "Resend",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authRetryCountdown",
    "tr": "{time} sonra tekrar dene",
    "en": "Try again in {time}",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authSendCodeAction",
    "tr": "Kod gönder",
    "en": "Send code",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authSpamHint",
    "tr": "Kod görünmüyorsa spam klasörünü de kontrol et.",
    "en": "If you cannot see the code, check your spam folder too.",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authUseExistingCode",
    "tr": "Daha önce gelen kodu kullan",
    "en": "Use the code already sent",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "authVerifyCodeAction",
    "tr": "Kodu doğrula",
    "en": "Verify code",
    "source": "lib/src/auth/presentation/auth_screen.dart"
  },
  {
    "key": "averageCaloriesSuffix",
    "tr": " kcal ortalama",
    "en": " kcal average",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "calorieAmount",
    "tr": "{amount} kcal",
    "en": "{amount} kcal",
    "source": "lib/src/widgets/meal_list_tile.dart"
  },
  {
    "key": "calorieGoalDefaultNote",
    "tr": "Önerilen hedefi profilinden değiştirebilirsin.",
    "en": "You can change the suggested target in your profile.",
    "source": "lib/src/widgets/daily_summary_card.dart"
  },
  {
    "key": "calorieGoalLabel",
    "tr": "Hedef",
    "en": "Goal",
    "source": "lib/src/widgets/daily_summary_card.dart"
  },
  {
    "key": "caloriesConsumedLabel",
    "tr": "Alınan",
    "en": "Consumed",
    "source": "lib/src/widgets/daily_summary_card.dart"
  },
  {
    "key": "caloriesPer100g",
    "tr": "{amount} kcal / 100 g",
    "en": "{amount} kcal / 100 g",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "caloriesRemainingRingLabel",
    "tr": "kcal kaldı",
    "en": "kcal left",
    "source": "lib/src/widgets/daily_summary_card.dart"
  },
  {
    "key": "calorieSummarySemantics",
    "tr": "{remaining} kcal kaldı. {current} / {goal} kcal alındı.",
    "en": "{remaining} kcal left. {current} of {goal} kcal consumed.",
    "source": "lib/src/widgets/daily_summary_card.dart"
  },
  {
    "key": "calorieTrendSemantics",
    "tr": "{days} günlük kalori trendi",
    "en": "{days}-day calorie trend",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "calorieTrendSummarySemantics",
    "tr": "{headline}: ortalama {average} kcal, en düşük {lowest} kcal, en yüksek {highest} kcal, {direction}",
    "en": "{headline}: {average} kcal average, {lowest} kcal lowest, {highest} kcal highest, {direction}",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "cameraOpenErrorTitle",
    "tr": "Kamera açılamadı",
    "en": "Could not open camera",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "cameraPreparing",
    "tr": "Kamera hazırlanıyor",
    "en": "Preparing camera",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "cameraPreparingBody",
    "tr": "Birazdan doğrudan çekim ekranına geçeceksin.",
    "en": "You will go directly to the camera in a moment.",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "cancelAnalysisAction",
    "tr": "Analizi iptal et",
    "en": "Cancel analysis",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "catalogCandidateSummary",
    "tr": "{alias} · {grams} g",
    "en": "{alias} · {grams} g",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "catalogSearchAction",
    "tr": "Katalogda ara ve düzelt",
    "en": "Search catalog and correct",
    "source": "ARB"
  },
  {
    "key": "catalogSearchEmpty",
    "tr": "Eşleşen bir yiyecek bulamadık.",
    "en": "No matching food was found.",
    "source": "ARB"
  },
  {
    "key": "catalogSearchError",
    "tr": "Katalog araması şu anda kullanılamıyor.",
    "en": "Catalog search is currently unavailable.",
    "source": "ARB"
  },
  {
    "key": "catalogSearchExplanation",
    "tr": "AI emin olamadı. Katalogdan seçtiğinde besin değerlerini doğrulanmış kaynaktan hesaplarız.",
    "en": "AI was not confident. Choose from the catalog to calculate nutrition from a verified source.",
    "source": "ARB"
  },
  {
    "key": "catalogSearchHint",
    "tr": "Yiyecek adı",
    "en": "Food name",
    "source": "ARB"
  },
  {
    "key": "catalogSearchTitle",
    "tr": "Doğru yiyeceği bul",
    "en": "Find the right food",
    "source": "ARB"
  },
  {
    "key": "changeTimeAction",
    "tr": "Değiştir",
    "en": "Change",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "chooseAnotherPhotoAction",
    "tr": "Başka fotoğraf",
    "en": "Another photo",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "chooseFromGallery",
    "tr": "Galeriden seç",
    "en": "Choose from gallery",
    "source": "lib/src/app.dart"
  },
  {
    "key": "commonBack",
    "tr": "Geri",
    "en": "Back",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "commonCancel",
    "tr": "Vazgeç",
    "en": "Cancel",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "commonClose",
    "tr": "Kapat",
    "en": "Close",
    "source": "ARB"
  },
  {
    "key": "commonContinue",
    "tr": "Devam et",
    "en": "Continue",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "commonRetry",
    "tr": "Tekrar dene",
    "en": "Try again",
    "source": "lib/src/onboarding/presentation/profile_completion_screen.dart"
  },
  {
    "key": "commonUndo",
    "tr": "Geri al",
    "en": "Undo",
    "source": "lib/src/app.dart"
  },
  {
    "key": "comparisonHigher",
    "tr": "Günlük kalori ortalaman önceki döneme göre %{percent} daha yüksek.",
    "en": "Your daily calorie average is {percent}% higher than the previous period.",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "comparisonLower",
    "tr": "Günlük kalori ortalaman önceki döneme göre %{percent} daha düşük.",
    "en": "Your daily calorie average is {percent}% lower than the previous period.",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "comparisonSame",
    "tr": "Günlük kalori ortalaman önceki dönemle aynı seviyede.",
    "en": "Your daily calorie average is unchanged from the previous period.",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "comparisonWaiting",
    "tr": "Karşılaştırma için önceki dönem kayıtlarını bekliyoruz.",
    "en": "Waiting for previous-period entries to compare.",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "currentEntries",
    "tr": "Mevcut kayıtlar",
    "en": "Current entries",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "dailyAverageTitle",
    "tr": "Günlük ortalama",
    "en": "Daily average",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "dailyCaloriesTitle",
    "tr": "Günlük kalori",
    "en": "Daily calories",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "dailyGoalCalories",
    "tr": "{calories} kcal",
    "en": "{calories} kcal",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "dailyGoalLabel",
    "tr": "Günlük hedef",
    "en": "Daily goal",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "dailyGoalSourceDefault",
    "tr": "Uygulamanın varsayılan hedefi. Başlangıç sorularını yeniden yanıtlayarak değiştirebilirsin.",
    "en": "The app default. Answer the setup questions again to change it.",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "dailyGoalSourceOnboarding",
    "tr": "Başlangıçta seçtiğin hedefe göre hesaplandı.",
    "en": "Calculated from the target you chose during setup.",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "dailySummaryDetails",
    "tr": "Detaylar",
    "en": "Details",
    "source": "lib/src/widgets/daily_summary_card.dart"
  },
  {
    "key": "dailySummaryTitle",
    "tr": "Özet",
    "en": "Summary",
    "source": "lib/src/widgets/daily_summary_card.dart"
  },
  {
    "key": "daysAgo",
    "tr": "{days} gün önce",
    "en": "{days} days ago",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "deleteAccountAcknowledge",
    "tr": "Bu işlemin geri alınamayacağını anlıyorum.",
    "en": "I understand this cannot be undone.",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "deleteAccountAction",
    "tr": "Hesabı sil",
    "en": "Delete account",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "deleteAccountConfirmBody",
    "tr": "Hesabın, kayıtlı tüm öğünlerin, öğün fotoğrafların ve başlangıç tercihlerin sunucudan kalıcı olarak silinir. Bu işlem geri alınamaz ve verilerin kurtarılamaz.",
    "en": "Your account, every logged meal, your meal photos and your setup preferences are permanently removed from the server. This cannot be undone and the data cannot be recovered.",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "deleteAccountConfirmTitle",
    "tr": "Hesabın kalıcı olarak silinsin mi?",
    "en": "Permanently delete your account?",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "deleteAccountError",
    "tr": "Hesap silinemedi. Bağlantını kontrol edip tekrar dene.",
    "en": "Could not delete your account. Check your connection and try again.",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "deleteAccountFinalAction",
    "tr": "Hesabı kalıcı olarak sil",
    "en": "Delete permanently",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "deleteAccountFinalBody",
    "tr": "Hesabını sildiğimizde verilerini geri getiremeyiz.",
    "en": "Once your account is deleted we cannot restore your data.",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "deleteAccountFinalTitle",
    "tr": "Son onay",
    "en": "Final confirmation",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "deleteMealAction",
    "tr": "Öğünü sil",
    "en": "Delete meal",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "deleteMealConfirmAction",
    "tr": "Evet, sil",
    "en": "Yes, delete",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "deleteMealConfirmBody",
    "tr": "Günlük toplamların bu öğün olmadan yeniden hesaplanacak.",
    "en": "Your daily totals will be recalculated without this meal.",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "deleteMealConfirmTitle",
    "tr": "Bu öğün silinsin mi?",
    "en": "Delete this meal?",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "demoCheeseClarify",
    "tr": "Miktarı netleştirelim",
    "en": "Let’s clarify the amount",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "demoCheeseQuestion",
    "tr": "Yaklaşık ne kadardı?",
    "en": "About how much was it?",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "demoCheeseTitle",
    "tr": "Beyaz peynir",
    "en": "White cheese",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "demoEggsDetail",
    "tr": "2 adet",
    "en": "2 pieces",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "demoEggsTitle",
    "tr": "2 yumurta",
    "en": "2 eggs",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "demoMacros",
    "tr": "24 g protein · 32 g karbonhidrat · 21 g yağ",
    "en": "24 g protein · 32 g carbs · 21 g fat",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "demoSimitDetail",
    "tr": "½ adet",
    "en": "½ piece",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "demoSimitTitle",
    "tr": "Yarım simit",
    "en": "Half a simit",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "describeMealInsteadAction",
    "tr": "Fotoğrafsız devam et",
    "en": "Continue without a photo",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "detectedFoodsTitle",
    "tr": "Bulunan yiyecekler",
    "en": "Detected foods",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "eatenAtNow",
    "tr": "Şimdi yendi",
    "en": "Eaten now",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "eatenAtValue",
    "tr": "{date} · {time}",
    "en": "{date} · {time}",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "fastestLoggingMethod",
    "tr": "En hızlı kayıt yöntemi",
    "en": "The fastest way to log",
    "source": "lib/src/app.dart"
  },
  {
    "key": "foodCount",
    "tr": "{count} yiyecek",
    "en": "{count} foods",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "foodsTitle",
    "tr": "Yiyecekler",
    "en": "Foods",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "goalMacroSummaryValues",
    "tr": "{protein} g protein · {carbs} g karbonhidrat · {fat} g yağ",
    "en": "{protein} g protein · {carbs} g carbs · {fat} g fat",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "gramAmount",
    "tr": "{amount} g",
    "en": "{amount} g",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "highestCalorieMeal",
    "tr": "En yüksek kalorili öğün",
    "en": "Highest-calorie meal",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "highestMealSummary",
    "tr": "{meal} · {calories} kcal",
    "en": "{meal} · {calories} kcal",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "historyDayFilterSemantics",
    "tr": "{date} gününü göster",
    "en": "Show {date}",
    "source": "lib/src/features/history_screen.dart"
  },
  {
    "key": "historyEmptyAction",
    "tr": "İlk öğünü ekle",
    "en": "Add your first meal",
    "source": "lib/src/features/history_screen.dart"
  },
  {
    "key": "historyEmptyBody",
    "tr": "Kaydettiğin öğünler burada günlere göre görünecek.",
    "en": "Meals you log will appear here grouped by day.",
    "source": "lib/src/features/history_screen.dart"
  },
  {
    "key": "historyEmptyTitle",
    "tr": "Henüz geçmiş öğün yok",
    "en": "No meal history yet",
    "source": "lib/src/features/history_screen.dart"
  },
  {
    "key": "historySummary",
    "tr": "{count} öğün · {protein} g protein",
    "en": "{count} meals · {protein} g protein",
    "source": "lib/src/features/history_screen.dart"
  },
  {
    "key": "historyTitle",
    "tr": "Geçmiş",
    "en": "History",
    "source": "lib/src/features/history_screen.dart"
  },
  {
    "key": "humanLoopMessage",
    "tr": "Emin olduğumuzu çözeriz. Emin olmadığımızda yalnızca gerekli şeyi sana sorarız.",
    "en": "We resolve what we know. When unsure, we ask only what matters.",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "language",
    "tr": "Dil",
    "en": "Language",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "languageEnglish",
    "tr": "İngilizce",
    "en": "English",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "languagePickerTitle",
    "tr": "Uygulama dili",
    "en": "App language",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "languageSystem",
    "tr": "Cihaz dili",
    "en": "System language",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "languageTurkish",
    "tr": "Türkçe",
    "en": "Turkish",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "macroCarbs",
    "tr": "Karbonhidrat",
    "en": "Carbs",
    "source": "ARB"
  },
  {
    "key": "macroFat",
    "tr": "Yağ",
    "en": "Fat",
    "source": "ARB"
  },
  {
    "key": "macroGoalProgress",
    "tr": "{current} / {goal} g",
    "en": "{current} / {goal} g",
    "source": "lib/src/widgets/daily_summary_card.dart"
  },
  {
    "key": "macroGoalSemantics",
    "tr": "{macro}: {current} / {goal} gram",
    "en": "{macro}: {current} of {goal} grams",
    "source": "lib/src/widgets/daily_summary_card.dart"
  },
  {
    "key": "macroProtein",
    "tr": "Protein",
    "en": "Protein",
    "source": "ARB"
  },
  {
    "key": "mealActionsMenu",
    "tr": "Öğün işlemleri",
    "en": "Meal actions",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "mealAddPhoto",
    "tr": "Öğün fotoğrafı ekle",
    "en": "Add meal photo",
    "source": "ARB"
  },
  {
    "key": "mealAnalyze",
    "tr": "Öğünü analiz et",
    "en": "Analyze meal",
    "source": "ARB"
  },
  {
    "key": "mealAnalyzingAmbiguity",
    "tr": "Belirsizlikler kontrol ediliyor",
    "en": "Checking uncertainty",
    "source": "ARB"
  },
  {
    "key": "mealAnalyzingFoods",
    "tr": "Yiyecekler bulunuyor",
    "en": "Finding foods",
    "source": "ARB"
  },
  {
    "key": "mealAnalyzingPortions",
    "tr": "Porsiyonlar eşleştiriliyor",
    "en": "Matching portions",
    "source": "ARB"
  },
  {
    "key": "mealAnalyzingSummary",
    "tr": "Yiyecekler ve porsiyonlar tahmin ediliyor.",
    "en": "Estimating foods and portions.",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "mealCamera",
    "tr": "Fotoğraf çek",
    "en": "Take photo",
    "source": "ARB"
  },
  {
    "key": "mealCatalogNutrition",
    "tr": "Besin değerleri katalogdan hesaplanacak.",
    "en": "Nutrition will be calculated from the catalog.",
    "source": "ARB"
  },
  {
    "key": "mealCheckAmount",
    "tr": "Miktarı kontrol et",
    "en": "Check amount",
    "source": "ARB"
  },
  {
    "key": "mealCheckType",
    "tr": "Türü kontrol et",
    "en": "Check type",
    "source": "ARB"
  },
  {
    "key": "mealCheeseAmountExplanation",
    "tr": "30 g tahmin ettik. En yakın miktarı seçebilirsin.",
    "en": "We estimated 30 g. Choose the closest amount.",
    "source": "ARB"
  },
  {
    "key": "mealCheeseAmountQuestion",
    "tr": "Peynir ne kadardı?",
    "en": "How much cheese was it?",
    "source": "ARB"
  },
  {
    "key": "mealComposeSubtitle",
    "tr": "Günlük konuşur gibi anlat. Miktarları biliyorsan ekle; bilmiyorsan önemli noktaları birlikte netleştiririz.",
    "en": "Describe it naturally. Add amounts if you know them; if not, we’ll clarify what matters.",
    "source": "ARB"
  },
  {
    "key": "mealComposeTitle",
    "tr": "Ne yedin?",
    "en": "What did you eat?",
    "source": "ARB"
  },
  {
    "key": "mealContainsEstimates",
    "tr": "tahmin içeriyor",
    "en": "contains estimates",
    "source": "lib/src/widgets/meal_list_tile.dart"
  },
  {
    "key": "mealCount",
    "tr": "{count} öğün",
    "en": "{count} meals",
    "source": "lib/src/features/today_screen.dart"
  },
  {
    "key": "mealDetailTitle",
    "tr": "Öğün detayı",
    "en": "Meal details",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "mealErrorInvalidRequest",
    "tr": "Açıklamayı anlayamadık. Daha kısa ve net yazmayı dene.",
    "en": "We could not understand the description. Try making it shorter and clearer.",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "mealErrorNoMatch",
    "tr": "Bu yiyeceği katalogda güvenle eşleştiremedik. Daha açık tarif etmeyi dene.",
    "en": "We could not confidently match this food. Try describing it more clearly.",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "mealErrorRateLimited",
    "tr": "Çok hızlı deneme yaptın. Biraz bekleyip tekrar dene.",
    "en": "You tried too quickly. Wait a moment and retry.",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "mealErrorUnauthenticated",
    "tr": "Oturumun yenilenmeli. Tekrar giriş yapıp deneyebilirsin.",
    "en": "Your session needs to be refreshed. Sign in again and retry.",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "mealErrorUnavailable",
    "tr": "Öğünü analiz edemedik. Bağlantını kontrol edip tekrar dene.",
    "en": "We could not analyze the meal. Check your connection and try again.",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "mealEstimatedTotal",
    "tr": "Tahmini toplam",
    "en": "Estimated total",
    "source": "ARB"
  },
  {
    "key": "mealFoodCount",
    "tr": "{time} · {count} yiyecek",
    "en": "{time} · {count} foods",
    "source": "lib/src/features/history_screen.dart"
  },
  {
    "key": "mealFoundCount",
    "tr": "{count} yiyecek bulduk",
    "en": "{count, plural, =1{We found 1 food} other{We found {count} foods}}",
    "source": "ARB"
  },
  {
    "key": "mealGallery",
    "tr": "Galeriden seç",
    "en": "Choose from library",
    "source": "ARB"
  },
  {
    "key": "mealInputHint",
    "tr": "Örn. 2 yumurta, biraz beyaz peynir ve yarım simit",
    "en": "e.g. 2 eggs, some white cheese and half a bagel",
    "source": "ARB"
  },
  {
    "key": "mealLog",
    "tr": "Öğünü kaydet",
    "en": "Log meal",
    "source": "ARB"
  },
  {
    "key": "mealMatchedCount",
    "tr": "{count} yiyecek eşleşti",
    "en": "{count, plural, =1{1 food matched} other{{count} foods matched}}",
    "source": "ARB"
  },
  {
    "key": "mealNameBreakfast",
    "tr": "Kahvaltı",
    "en": "Breakfast",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "mealNameDinner",
    "tr": "Akşam yemeği",
    "en": "Dinner",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "mealNameLunch",
    "tr": "Öğle yemeği",
    "en": "Lunch",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "mealNameSnack",
    "tr": "Atıştırma",
    "en": "Snack",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "mealPhotoError",
    "tr": "Bu fotoğrafı açamadık. Başka bir fotoğraf dene.",
    "en": "We couldn’t open that photo. Try another one.",
    "source": "ARB"
  },
  {
    "key": "mealPhotoHint",
    "tr": "Net ve üstten çekilmiş bir fotoğraf ekle. Kısa bir açıklama doğruluğu artırır.",
    "en": "Add a clear overhead photo. A short description improves accuracy.",
    "source": "ARB"
  },
  {
    "key": "mealPhotoLabel",
    "tr": "{meal} fotoğrafı",
    "en": "Photo of {meal}",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "mealPhotoMissing",
    "tr": "{meal} · fotoğraf yok",
    "en": "{meal} · no photo",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "mealPhotoSelected",
    "tr": "Öğün fotoğrafı seçildi",
    "en": "Meal photo selected",
    "source": "ARB"
  },
  {
    "key": "mealPhotoTooLarge",
    "tr": "Fotoğraf çok büyük. 8 MB'den küçük bir fotoğraf seç.",
    "en": "That photo is too large. Choose one under 8 MB.",
    "source": "ARB"
  },
  {
    "key": "mealQuickEggCheeseLabel",
    "tr": "2 yumurta · peynir · ½ simit",
    "en": "2 eggs · cheese · ½ bagel",
    "source": "ARB"
  },
  {
    "key": "mealQuickEggCheeseValue",
    "tr": "2 yumurta, biraz beyaz peynir ve yarım simit",
    "en": "2 eggs, some white cheese and half a bagel",
    "source": "ARB"
  },
  {
    "key": "mealQuickTry",
    "tr": "Hızlı dene",
    "en": "Quick try",
    "source": "ARB"
  },
  {
    "key": "mealQuickYogurtLabel",
    "tr": "Bir kase yoğurt",
    "en": "A bowl of yogurt",
    "source": "ARB"
  },
  {
    "key": "mealQuickYogurtValue",
    "tr": "Bir kase yoğurt yedim",
    "en": "I ate a bowl of yogurt",
    "source": "ARB"
  },
  {
    "key": "mealReadyToLog",
    "tr": "Her şey hazır. Kaydetmeden önce son kez kontrol et.",
    "en": "Everything is ready. Review once more before logging.",
    "source": "ARB"
  },
  {
    "key": "mealRemovePhoto",
    "tr": "Fotoğrafı kaldır",
    "en": "Remove photo",
    "source": "ARB"
  },
  {
    "key": "mealResultReadyTitle",
    "tr": "Öğünün hazır",
    "en": "Your meal is ready",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "mealReviewImpactCount",
    "tr": "{count} nokta sonucu etkileyebilir.",
    "en": "{count, plural, =1{1 detail may affect the result.} other{{count} details may affect the result.}}",
    "source": "ARB"
  },
  {
    "key": "mealReviewPoints",
    "tr": "{count} noktayı kontrol et",
    "en": "{count, plural, =1{Review 1 detail} other{Review {count} details}}",
    "source": "ARB"
  },
  {
    "key": "mealReviewReadyBody",
    "tr": "Yiyecekleri ve toplamları senin için eşleştirdik.",
    "en": "We matched the foods and totals for you.",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "mealReviewTitle",
    "tr": "Öğünü kontrol et",
    "en": "Review meal",
    "source": "ARB"
  },
  {
    "key": "mealSaveDeviceError",
    "tr": "Öğün cihazına kaydedilemedi.",
    "en": "The meal could not be saved to your device.",
    "source": "lib/src/app.dart"
  },
  {
    "key": "mealSavedMessage",
    "tr": "{meal} kaydedildi",
    "en": "{meal} saved",
    "source": "lib/src/app.dart"
  },
  {
    "key": "mealStepAnalyzingTitle",
    "tr": "Analiz",
    "en": "Analysis",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "mealStepComposeTitle",
    "tr": "Öğün ekle",
    "en": "Add meal",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "mealStepReviewTitle",
    "tr": "Kontrol",
    "en": "Review",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "mealTimeOnDate",
    "tr": "{date} · {time}",
    "en": "{date} · {time}",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "mealTimeToday",
    "tr": "Bugün · {time}",
    "en": "Today · {time}",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "mealTotalApproximate",
    "tr": "Toplam yaklaşık — bazı miktarlar tahmin.",
    "en": "Total is approximate — some amounts are estimates.",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "mealTypeExplanation",
    "tr": "Doğru gıdayı seçmek kalori ve makroları doğrudan etkiler.",
    "en": "Choosing the correct food directly affects calories and macros.",
    "source": "ARB"
  },
  {
    "key": "mealTypeQuestion",
    "tr": "Hangisine daha yakındı?",
    "en": "Which one was closest?",
    "source": "ARB"
  },
  {
    "key": "mealVoiceInput",
    "tr": "Sesle ekle",
    "en": "Add by voice",
    "source": "ARB"
  },
  {
    "key": "metricCalories",
    "tr": "Kalori",
    "en": "Calories",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "metricMeals",
    "tr": "Öğün",
    "en": "Meals",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "navAddMeal",
    "tr": "Öğün Ekle",
    "en": "Add Meal",
    "source": "lib/src/widgets/liquid_glass_bottom_bar.dart"
  },
  {
    "key": "navAddMealShort",
    "tr": "Ekle",
    "en": "Add",
    "source": "lib/src/widgets/liquid_glass_bottom_bar.dart"
  },
  {
    "key": "navAnalysis",
    "tr": "Analiz",
    "en": "Analysis",
    "source": "lib/src/widgets/liquid_glass_bottom_bar.dart"
  },
  {
    "key": "navHistory",
    "tr": "Geçmiş",
    "en": "History",
    "source": "lib/src/widgets/liquid_glass_bottom_bar.dart"
  },
  {
    "key": "navProfile",
    "tr": "Profil",
    "en": "Profile",
    "source": "lib/src/widgets/liquid_glass_bottom_bar.dart"
  },
  {
    "key": "navToday",
    "tr": "Günlük",
    "en": "Today",
    "source": "lib/src/widgets/liquid_glass_bottom_bar.dart"
  },
  {
    "key": "notNowAction",
    "tr": "Şimdi değil",
    "en": "Not now",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "nutritionTrendTitle",
    "tr": "Beslenme trendin",
    "en": "Your nutrition trend",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "onboardingContinue",
    "tr": "Devam et",
    "en": "Continue",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "onboardingExistingAccount",
    "tr": "Zaten hesabım var",
    "en": "I already have an account",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "onboardingHeroSemantics",
    "tr": "Yumurta, simit ve beyaz peynirden oluşan kahvaltı tabağı",
    "en": "A breakfast plate with eggs, simit, and white cheese",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "onboardingProgressSemantics",
    "tr": "3 adımdan {step}. adım",
    "en": "Step {step} of 3",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "onboardingSeeHowAction",
    "tr": "Nasıl çalıştığını gör",
    "en": "See how it works",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "onboardingStartAction",
    "tr": "Başlayalım",
    "en": "Let’s begin",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "onboardingWelcomeBody",
    "tr": "Fotoğrafını çek veya ne yediğini yaz. Gerisini birlikte netleştiririz.",
    "en": "Take a photo or write what you ate. We clarify the rest together.",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "onboardingWelcomeTitle",
    "tr": "Yemeğini kaydetmenin daha doğal yolu.",
    "en": "A more natural way to log your meals.",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "openCameraAction",
    "tr": "Kamerayı aç",
    "en": "Open camera",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "orEnterGrams",
    "tr": "veya gram gir",
    "en": "or enter grams",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "period30Days",
    "tr": "30 Gün",
    "en": "30 Days",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "period3Months",
    "tr": "3 Ay",
    "en": "3 Months",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "period7Days",
    "tr": "7 Gün",
    "en": "7 Days",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "periodSummaryTitle",
    "tr": "Dönem özeti",
    "en": "Period summary",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "photoContextHint",
    "tr": "Pilav tavuğun altında, sos yoğurtlu...",
    "en": "The rice is under the chicken, the sauce is yogurt-based...",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "photoContextQuestion",
    "tr": "Bir detay eklemek ister misin?",
    "en": "Would you like to add a detail?",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "photoGuideBody",
    "tr": "Yemeğin tamamı kadrajda ve iyi ışıkta olsun. Gerisini biz çözeriz.",
    "en": "Keep the whole meal in frame and well lit. We handle the rest.",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "photoGuideDistance",
    "tr": "Çok yakından çekme",
    "en": "Do not shoot too close",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "photoGuideImageSemantics",
    "tr": "Kadrajın tamamında görünen, iyi aydınlatılmış bir kahvaltı tabağı örneği",
    "en": "Example of a well-lit breakfast plate fully visible in frame",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "photoGuideLight",
    "tr": "İyi ışık kullan",
    "en": "Use good lighting",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "photoGuideTitle",
    "tr": "Tabağını net görelim.",
    "en": "Let us see the whole plate.",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "photoGuideWholePlate",
    "tr": "Tabağın tamamı görünsün",
    "en": "Keep the whole plate visible",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "photoReadyBody",
    "tr": "Analizden önce tabağın tamamının göründüğünü kontrol et.",
    "en": "Make sure the whole plate is visible before analysis.",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "photoReadyTitle",
    "tr": "Fotoğraf hazır",
    "en": "Photo ready",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "portionEditBody",
    "tr": "Miktarı değiştirince kalori ve makrolar yeniden hesaplanır.",
    "en": "Calories and macros are recalculated when you change the amount.",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "portionEstimate",
    "tr": "Tahmin",
    "en": "Estimate",
    "source": "ARB"
  },
  {
    "key": "portionExact",
    "tr": "Tam miktar gir",
    "en": "Enter exact amount",
    "source": "ARB"
  },
  {
    "key": "portionGramsRangeError",
    "tr": "{min} ile {max} g arasında bir değer gir.",
    "en": "Enter a value between {min} and {max} g.",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "portionGramsRangeHint",
    "tr": "{min}-{max} g",
    "en": "{min}-{max} g",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "portionInvalidNumber",
    "tr": "Sayı olarak bir miktar gir.",
    "en": "Enter the amount as a number.",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "portionLarge",
    "tr": "Fazla",
    "en": "Large",
    "source": "ARB"
  },
  {
    "key": "portionOutOfRange",
    "tr": "{min}-{max} g arasında bir miktar gir.",
    "en": "Enter an amount between {min} and {max} g.",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "portionQuestion",
    "tr": "{item} miktarı",
    "en": "{item} amount",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "portionQuestionBody",
    "tr": "En yakın seçeneği seç. Besin değerlerini buna göre yeniden hesaplayacağız.",
    "en": "Choose the closest option. We will recalculate the nutrition accordingly.",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "portionRegular",
    "tr": "Normal",
    "en": "Regular",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "portionSavedAmount",
    "tr": "Kayıtlı miktar: {amount} g",
    "en": "Saved amount: {amount} g",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "portionSavedAmountDelta",
    "tr": "Kayıtlı miktar: {amount} g · {delta} g",
    "en": "Saved amount: {amount} g · {delta} g",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "portionSmall",
    "tr": "Az",
    "en": "Small",
    "source": "ARB"
  },
  {
    "key": "profileAccount",
    "tr": "Hesap",
    "en": "Account",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "profilePreferences",
    "tr": "Tercihler",
    "en": "Preferences",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "profileSaveError",
    "tr": "Tercihler kaydedilemedi. Bağlantını kontrol edip tekrar dene.",
    "en": "Preferences could not be saved. Check your connection and try again.",
    "source": "lib/src/onboarding/presentation/profile_completion_screen.dart"
  },
  {
    "key": "profileSavingPreferences",
    "tr": "Başlangıç tercihlerin kaydediliyor…",
    "en": "Saving your initial preferences…",
    "source": "lib/src/onboarding/presentation/profile_completion_screen.dart"
  },
  {
    "key": "profileTitle",
    "tr": "Profil",
    "en": "Profile",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "proteinAmount",
    "tr": "{amount} g protein",
    "en": "{amount} g protein",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "quickAddBody",
    "tr": "Fotoğrafla başla; gerekirse düzelt",
    "en": "Start with a photo, adjust if needed",
    "source": "lib/src/features/today_screen.dart"
  },
  {
    "key": "quickAddTitle",
    "tr": "Yemeğini göster",
    "en": "Show your meal",
    "source": "lib/src/features/today_screen.dart"
  },
  {
    "key": "recordCount",
    "tr": "{count} kayıt",
    "en": "{count} entries",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "removeFoodAction",
    "tr": "Yiyeceği kaldır",
    "en": "Remove food",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "retakePhotoAction",
    "tr": "Yeniden çek",
    "en": "Retake",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "scanGuideBody",
    "tr": "Tabağın tamamı görünsün; telefonu mümkün olduğunca yukarıdan ve sabit tut.",
    "en": "Keep the entire plate visible and hold your phone steady from above.",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "scanGuideImageSemantics",
    "tr": "Telefon kamerasıyla yukarıdan taranan yemek tabağı",
    "en": "A plate of food scanned from above with a phone camera",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "scanGuideTitle",
    "tr": "Yemeğini nasıl taratırsın?",
    "en": "How to scan your meal",
    "source": "lib/src/features/meal_flow.dart"
  },
  {
    "key": "signOutAction",
    "tr": "Oturumu kapat",
    "en": "Sign out",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "signOutConfirmBody",
    "tr": "Hesabın ve kayıtlı öğünlerin silinmez. Tekrar giriş yaptığında her şey yerinde olur.",
    "en": "Your account and logged meals are kept. Everything will be here when you sign in again.",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "signOutConfirmTitle",
    "tr": "Oturum kapatılsın mı?",
    "en": "Sign out?",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "signOutError",
    "tr": "Oturum kapatılamadı. Bağlantını kontrol edip tekrar dene.",
    "en": "Could not sign out. Check your connection and try again.",
    "source": "lib/src/features/profile_screen.dart"
  },
  {
    "key": "takePhoto",
    "tr": "Fotoğraf çek",
    "en": "Take photo",
    "source": "lib/src/app.dart"
  },
  {
    "key": "textDemoBody",
    "tr": "Nasıl söylüyorsan öyle.",
    "en": "Just as you would say it.",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "textDemoMeal",
    "tr": "2 yumurta, yarım simit ve biraz beyaz peynir yedim",
    "en": "I ate 2 eggs, half a simit, and some white cheese",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "textDemoPlaceholder",
    "tr": "Ne yedin?",
    "en": "What did you eat?",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "textDemoTitle",
    "tr": "İstersen sadece yaz.",
    "en": "Or simply write it.",
    "source": "lib/src/onboarding/presentation/onboarding_screen.dart"
  },
  {
    "key": "todayEmptyAction",
    "tr": "İlk öğünü ekle",
    "en": "Add your first meal",
    "source": "lib/src/features/today_screen.dart"
  },
  {
    "key": "todayEmptyBody",
    "tr": "İlk kaydınla günlük özetin oluşmaya başlayacak.",
    "en": "Your daily summary will appear after your first entry.",
    "source": "lib/src/features/today_screen.dart"
  },
  {
    "key": "todayEmptyTitle",
    "tr": "Henüz öğün eklemedin",
    "en": "No meals yet",
    "source": "lib/src/features/today_screen.dart"
  },
  {
    "key": "todayEntry",
    "tr": "Bugünkü kayıt",
    "en": "Today's entry",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "todayMealsTitle",
    "tr": "Bugünün öğünleri",
    "en": "Today's meals",
    "source": "lib/src/features/today_screen.dart"
  },
  {
    "key": "todayTitle",
    "tr": "Bugün",
    "en": "Today",
    "source": "lib/src/features/today_screen.dart"
  },
  {
    "key": "trendDirectionFalling",
    "tr": "dönem boyunca düşüyor",
    "en": "falling across the period",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "trendDirectionRising",
    "tr": "dönem boyunca yükseliyor",
    "en": "rising across the period",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "trendDirectionSteady",
    "tr": "dönem boyunca sabit",
    "en": "steady across the period",
    "source": "lib/src/features/analysis_screen.dart"
  },
  {
    "key": "updateAmountAction",
    "tr": "Miktarı güncelle",
    "en": "Update amount",
    "source": "lib/src/features/meal_detail_screen.dart"
  },
  {
    "key": "yogurtLight",
    "tr": "Light yoğurt",
    "en": "Light yogurt",
    "source": "ARB"
  },
  {
    "key": "yogurtStrained",
    "tr": "Süzme yoğurt",
    "en": "Strained yogurt",
    "source": "ARB"
  },
  {
    "key": "yogurtWhole",
    "tr": "Tam yağlı yoğurt",
    "en": "Whole milk yogurt",
    "source": "ARB"
  }
] as const
